/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/index/index" |
  "/pages/about/index" |
  "/subPages/ci/index" |
  "/subPages/create-uni/index" |
  "/subPages/feedback/index" |
  "/subPages/router/advanced-aftereach" |
  "/subPages/router/advanced-beforeeach" |
  "/subPages/router/advanced-guard-async" |
  "/subPages/router/advanced-guard-remove" |
  "/subPages/router/advanced-guard-return" |
  "/subPages/router/advanced-protected-target" |
  "/subPages/router/advanced-protected" |
  "/subPages/router/advanced" |
  "/subPages/router/api-reference-back" |
  "/subPages/router/api-reference" |
  "/subPages/router/essentials-navigation" |
  "/subPages/router/essentials-params" |
  "/subPages/router/essentials" |
  "/subPages/router/index" |
  "/subPages/router/router-advanced-protected-target" |
  "/subEcharts/echarts/index" |
  "/subAsyncEcharts/asyncEcharts/index";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/about/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module "virtual:uni-pages" {
  export type LocationUrl = _LocationUrl;
}
